### ISSUE TITLE
Fix verb with (-ing)

### ISSUE THREAD

**Issue by devTeaa** [devTeaa/devrant-unswear#3]
**Describe the bug**
Bad grammar for goodWords replaced with (-ing) ending

**Screenshots**
Original
![00](https://user-images.githubusercontent.com/38621036/51448554-00408000-1d5a-11e9-9b68-20922b74b780.PNG)

Results
![01](https://user-images.githubusercontent.com/38621036/51448562-0898bb00-1d5a-11e9-8da2-34949ddf31dc.PNG)

**Additional context**
Add regex to detect syllables

**Comment by devTeaa** [comment]
@voidpy any idea for this?

**Comment by voidpy** [comment]
I'll see what I can do. Do you have Telegram or Signal, perhaps?

**Comment by devTeaa** [comment]
@voidpy wire: @devtea, I think I'm just going to create verb tenses regex when I finally got time

**Comment by devTeaa** [comment]
Fixed with bfecad573895d57b0a6daa32445d2b149836a35b

@voidpy

**Comment by Parou** [comment]
I like how the ribbon is used before the word God in this case.
