### ISSUE TITLE
Script not functional on comments section. I am serious :D

### ISSUE THREAD

**Issue by kart-archive** [devTeaa/devrant-unswear#5]
**Describe the bug**
@devTeaa your script is not functional on the comments section.

**To Reproduce**
1. Go to dR
2. Click on a random rant with some swear word.
3. Scroll down.
4. Enable your script on Tampermonkey or whatever monkey you have.
4. You'll notice the swears are replaced by the script on the rant but not on the comments section.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/25691607/59191997-b1777380-8b9e-11e9-948d-71b0a3d941af.PNG)

**I literally found that out in your comment...............................Irony**

**PS**: I am stealing your issue template xD if you don't mind.

**Comment by devTeaa** [comment]
@KartSriv lol, thanks for mentioning it. I'll look into it when I'm free.

**Comment by ghost** [comment]
Kk

**Comment by kart-archive** [comment]
@aheisleycook It's been almost 2 years since I opened this issue lmaoooo also @devTeaa How are you?

**Comment by Parou** [comment]
> @aheisleycook It's been almost 2 years since I opened this issue lmaoooo also @devTeaa How are you?

The issue isn't that comments don't get replaced. In fact, in that thread that the screenshot is from, there is at least one comment that has a word replaced by the script. The issue is, that the RegEx' are not made case insensitive and therefore simply not replacing words that aren't their lowercase version, as shown in your screenshot.

It should work after you replace lines 24 - 26:
```JavaScript
 // Create badWords and verb with tenses regex
  let badWordsReg = RegExp(badWords.join("|"));
  let badWordsTenseReg = RegExp(`(${badWords.join("|")})+(ing|ed));
```

with
```JavaScript
  // Create badWords and verb with tenses regex
  let badWordsReg = RegExp(badWords.join("|"), "i");
  let badWordsTenseReg = RegExp(`(${badWords.join("|")})+(ing|ed)+`, "i");
```

**Comment by devTeaa** [comment]
Yeah, sorry for not keeping it updated, I've been really busy with work lately. I've been good @KartSriv
